In [1]:
from corpus import load_meta_data
from features import load_features

In [2]:
meta_data = load_meta_data()
meta_data

Book_Name  \
book_id                                                                      
pg10067                  The Mystery of the Boule Cabinet: A Detective ...   
pg1032                                                           The Pupil   
pg10379                                                     At Love's Cost   
pg10473                                             The Heart of the Range   
pg10812                                        The Worshipper of the Image   
...                                                                    ...   
pg766DickensDavidCopfld                                  David Copperfield   
pg786DickensHardTimes                                           Hard Times   
pg834DoyleMemoirsSherlk                          Memoirs of Shelock Holmes   
pg863Agatha1                               The Mysterious Affair at Styles   
pg98DickensTaleCities                                 A Tale of Two Cities   

                                   guten_genre               Author_Name  
book_id                                                                   
pg10067                  Detective and Mystery  Stevenson| Burton Egbert  
pg1032                                Literary              James| Henry  
pg10379                               Literary          Garvice| Charles  
pg10473                        Western Stories  White| William Patterson  
pg10812                               Literary     Gallienne| Richard Le  
...                                        ...                       ...  
pg766DickensDavidCopfld               Literary          Dickens| Charles  
pg786DickensHardTimes                 Literary          Dickens| Charles  
pg834DoyleMemoirsSherlk  Detective and Mystery             Connan| Doyle  
pg863Agatha1             Detective and Mystery          Christie| Agatha  
pg98DickensTaleCities                 Literary          Dickens| Charles  

[996 rows x 3 columns]

In [3]:
features = load_features()
features

book_id  title_word_count  title_avg_word_length  \
0                    pg10067                 9               4.777778   
1                     pg1032                 2               4.000000   
2                    pg10379                 3               4.000000   
3                    pg10473                 5               3.600000   
4                    pg10812                 5               4.600000   
..                       ...               ...                    ...   
991  pg766DickensDavidCopfld                 2               8.000000   
992    pg786DickensHardTimes                 2               4.500000   
993  pg834DoyleMemoirsSherlk                 4               5.500000   
994             pg863Agatha1                 5               5.400000   
995    pg98DickensTaleCities                 5               3.200000   

      ._count   !_count   ?_count   ,_count  ``_count  length  proper_names  \
0    0.047124  0.003927  0.007425  0.065670  0.028751   86326      0.002919   
1    0.034161  0.003822  0.005542  0.045963  0.016149   20930      0.004157   
2    0.036540  0.006190  0.005673  0.064081  0.017677  183689      0.002433   
3    0.063323  0.003170  0.009745  0.050225  0.031861  115440      0.003067   
4    0.040540  0.005314  0.004233  0.067206  0.016131   21263      0.003715   
..        ...       ...       ...       ...       ...     ...           ...   
991  0.034839  0.006531  0.004193  0.084033  0.000412  429805      0.003455   
992  0.038167  0.005037  0.004909  0.082862  0.000215  125474      0.006607   
993  0.045144  0.002106  0.005615  0.058558  0.021029  104000      0.005471   
994  0.056792  0.005689  0.011474  0.058872  0.030001   72598      0.003223   
995  0.035153  0.005978  0.005029  0.078704  0.013378   21079      0.008350   

     pos_sentiment  neu_sentiment  neg_sentiment  point_of_view  
0            0.104          0.800          0.096       0.644986  
1            0.143          0.779          0.078       0.272887  
2            0.156          0.759          0.085       0.456420  
3            0.100          0.824          0.076       0.575733  
4            0.163          0.715          0.122       0.318627  
..             ...            ...            ...            ...  
991          0.138          0.779          0.083       0.708288  
992          0.122          0.794          0.083       0.522765  
993          0.099          0.817          0.084       0.649575  
994          0.112          0.784          0.105       0.669434  
995          0.099          0.813          0.089       0.467312  

[996 rows x 14 columns]

In [4]:
labels = meta_data.guten_genre
num_genre = labels.nunique()
num_features = features.shape[1]-1

In [5]:
import imblearn
import numpy as np
import pandas as pd
int_labels = pd.factorize(meta_data.guten_genre)
features['guten_genre'] = int_labels[0]
overSampler = imblearn.over_sampling.RandomOverSampler()
sampled_features_and_labels = overSampler.fit_resample(features, labels.to_numpy())
sampled_features_and_labels[0]

Using TensorFlow backend.


book_id  title_word_count  title_avg_word_length   ._count   !_count  \
0     pg10067                 9               4.777778  0.047124  0.003927   
1      pg1032                 2               4.000000  0.034161  0.003822   
2     pg10379                 3               4.000000  0.036540  0.006190   
3     pg10473                 5               3.600000  0.063323  0.003170   
4     pg10812                 5               4.600000  0.040540  0.005314   
...       ...               ...                    ...       ...       ...   
7141  pg35078                 3               4.000000  0.053052  0.007277   
7142  pg35078                 3               4.000000  0.053052  0.007277   
7143  pg45618                 9               5.111111  0.050923  0.007559   
7144  pg46457                 6               4.666667  0.055904  0.004171   
7145  pg42423                 3               7.333333  0.045495  0.003727   

       ?_count   ,_count  ``_count  length  proper_names  pos_sentiment  \
0     0.007425  0.065670  0.028751   86326      0.002919          0.104   
1     0.005542  0.045963  0.016149   20930      0.004157          0.143   
2     0.005673  0.064081  0.017677  183689      0.002433          0.156   
3     0.009745  0.050225  0.031861  115440      0.003067          0.100   
4     0.004233  0.067206  0.016131   21263      0.003715          0.163   
...        ...       ...       ...     ...           ...            ...   
7141  0.005576  0.060283  0.015442   65275      0.003845          0.102   
7142  0.005576  0.060283  0.015442   65275      0.003845          0.102   
7143  0.007261  0.062262  0.031661   30163      0.002254          0.112   
7144  0.005323  0.048150  0.018912   78152      0.003954          0.090   
7145  0.002746  0.056152  0.012957   91768      0.002953          0.130   

      neu_sentiment  neg_sentiment  point_of_view  guten_genre  
0             0.800          0.096       0.644986            0  
1             0.779          0.078       0.272887            1  
2             0.759          0.085       0.456420            1  
3             0.824          0.076       0.575733            2  
4             0.715          0.122       0.318627            1  
...             ...            ...            ...          ...  
7141          0.799          0.099       0.466785            2  
7142          0.799          0.099       0.466785            2  
7143          0.758          0.130       0.619808            2  
7144          0.808          0.102       0.345463            2  
7145          0.786          0.083       0.447735            2  

[7146 rows x 15 columns]

In [6]:
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_features = sampled_features_and_labels[0]
scalable_axes = scaled_features.axes[1][1:-1]
scaled_features[scalable_axes] = scaler.fit_transform(sampled_features_and_labels[0][scalable_axes])
scaled_features

book_id  title_word_count  title_avg_word_length   ._count   !_count  \
0     pg10067          1.069037              -0.193615  0.429930 -0.152337   
1      pg1032         -0.960465              -0.825904 -0.904736 -0.187713   
2     pg10379         -0.670537              -0.825904 -0.659829  0.612160   
3     pg10473         -0.090679              -1.151081  2.097901 -0.407919   
4     pg10812         -0.090679              -0.338138 -0.247977  0.316402   
...       ...               ...                    ...       ...       ...   
7141  pg35078         -0.670537              -0.825904  1.040392  0.979435   
7142  pg35078         -0.670537              -0.825904  1.040392  0.979435   
7143  pg45618          1.069037               0.077366  0.821161  1.074717   
7144  pg46457          0.199250              -0.283942  1.333990 -0.069772   
7145  pg42423         -0.670537               1.883906  0.262246 -0.219970   

       ?_count   ,_count  ``_count    length  proper_names  pos_sentiment  \
0     1.294345  0.199349  1.744788  0.120565     -0.595611      -1.264918   
1     0.365802 -1.534659  0.137312 -1.250344     -0.190432       0.364152   
2     0.430077  0.059575  0.332156  2.161604     -0.754634       0.907175   
3     2.438336 -1.159603  2.141379  0.730887     -0.547364      -1.432002   
4    -0.279956  0.334526  0.135047 -1.243364     -0.334929       1.199572   
...        ...       ...       ...       ...           ...            ...   
7141  0.382629 -0.274586  0.047170 -0.320732     -0.292400      -1.348460   
7142  0.382629 -0.274586  0.047170 -0.320732     -0.292400      -1.348460   
7143  1.213086 -0.100516  2.115945 -1.056791     -0.813253      -0.930750   
7144  0.257653 -1.342223  0.489715 -0.050789     -0.256856      -1.849712   
7145 -1.013029 -0.638066 -0.269898  0.234646     -0.584501      -0.178872   

      neu_sentiment  neg_sentiment  point_of_view  guten_genre  
0          0.928045       0.045119       0.950449            0  
1          0.265870      -0.869150      -1.374870            1  
2         -0.364774      -0.513601      -0.227937            1  
3          1.684818      -0.970735       0.517673            2  
4         -1.752190       1.365730      -1.089030            1  
...             ...            ...            ...          ...  
7141       0.896513       0.197497      -0.163162            2  
7142       0.896513       0.197497      -0.163162            2  
7143      -0.396306       1.772072       0.793110            2  
7144       1.180303       0.349875      -0.921328            2  
7145       0.486595      -0.615186      -0.282213            2  

[7146 rows x 15 columns]

In [22]:
scaled_features = scaled_features.sample(frac=1).reset_index(drop=True) #shuffle
scaled_features

book_id  title_word_count  title_avg_word_length   ._count   !_count  \
0     pg33498          3.388467               0.417421  0.630661  2.213394   
1      pg1392         -0.380608               0.393511 -1.225256 -0.234995   
2     pg34619         -0.670537               0.799982 -0.176423 -0.965047   
3     pg34035         -0.960465              -0.012961  1.266331  0.480083   
4     pg13057         -0.960465               2.019397  1.294039 -0.534331   
...       ...               ...                    ...       ...       ...   
7141   pg6410          1.648894              -0.456384  1.557202  1.141163   
7142  pg42115          0.779108              -0.724286 -0.135022 -0.085646   
7143   pg8182         -0.090679              -0.988493 -0.823650 -0.615494   
7144    pg525         -0.670537               0.258020  0.476614 -0.097049   
7145  pg37430          1.069037               0.077366  1.046096 -0.315139   

       ?_count   ,_count  ``_count    length  proper_names  pos_sentiment  \
0     1.070078 -0.577969  0.433896 -0.338781      2.215013      -0.011788   
1    -0.964028  1.563953 -0.577527 -1.438615      3.024475       0.614778   
2    -1.065445  1.169554 -0.756508 -0.077014     -0.248570       1.199572   
3     1.351075 -0.376239  1.644615  0.573915     -0.723386      -0.262414   
4     0.675390 -0.645941 -1.901227 -0.309705      0.443889      -1.306689   
...        ...       ...       ...       ...           ...            ...   
7141  0.708881 -1.525358  0.956685  1.059821     -0.355404      -0.095330   
7142  0.240347  0.507829  0.935047  0.923434     -0.726445      -0.011788   
7143  0.130146  0.142601  0.067181 -0.811564     -0.855270      -1.264918   
7144 -0.939632  0.379365 -0.999416 -1.355999      1.621729      -1.181376   
7145  1.604701  0.177420  1.560417  0.039018      2.114452      -1.014292   

      neu_sentiment  neg_sentiment  point_of_view  guten_genre  
0          0.108209      -0.158052       0.102124            2  
1          0.076677      -0.869150       0.563653            4  
2         -0.711628      -0.310430      -0.163684            3  
3          0.991110      -1.275492       0.295065            0  
4          1.432560      -0.716772      -1.190759            1  
...             ...            ...            ...          ...  
7141      -0.364774       0.705424       0.148969            8  
7142      -0.144049       0.248290       0.012043            2  
7143       1.117239      -0.259637      -0.370366            3  
7144       0.770385       0.197497       1.501381            6  
7145       1.243367      -0.767564      -0.564947            8  

[7146 rows x 15 columns]

In [24]:
mask = msk = np.random.rand(len(scaled_features)) < 0.666
test_features = scaled_features[~msk]
train_features = scaled_features[msk]
print(scaled_features.shape, test_features.shape, train_features.shape)

(7146, 15) (2372, 15) (4774, 15)


In [25]:
#------------ a NN
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Dropout
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow import keras
from tensorflow.keras import layers
import matplotlib.pyplot as plt

In [320]:
batch_size = 8
epochs = 1
w_range = 0.1
learning_rate=0.005
layer_list = [
    Dense(128, input_dim = num_features, kernel_initializer=tf.initializers.RandomUniform(minval=-w_range, maxval=w_range)),
    Dense(64, activation='relu', kernel_initializer=tf.initializers.RandomUniform(minval=-w_range, maxval=w_range)),
    Dense(32, activation='relu', kernel_initializer=tf.initializers.RandomUniform(minval=-w_range, maxval=w_range)),
    Dense(num_genre)]
layer_list2 = [
    keras.Input(shape=(num_features)),
    layers.Dense(32, activation='relu'),
    layers.Dense(32, activation='relu'),
    layers.Dense(32, activation='relu'),
    layers.Dense(num_genre)]

opt = tf.optimizers.SGD(learning_rate=learning_rate)
loss_fn = tf.losses.SparseCategoricalCrossentropy(from_logits=True)

In [322]:
model = tf.keras.Sequential(layer_list)
model2 = tf.keras.Sequential(layer_list2)

In [313]:
model.summary()

Model: "sequential_55"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_199 (Dense)            (None, 128)               1792      
_________________________________________________________________
dense_200 (Dense)            (None, 64)                8256      
_________________________________________________________________
dense_201 (Dense)            (None, 32)                2080      
_________________________________________________________________
dense_202 (Dense)            (None, 9)                 297       
Total params: 12,425
Trainable params: 12,425
Non-trainable params: 0
_________________________________________________________________


In [299]:
#for tensorboard visualization:
import os
import datetime
from time import time
logdir = os.path.join("logs", "idl21" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S"))
train_writer = tf.summary.create_file_writer(os.path.join(logdir, "train"))
test_writer = tf.summary.create_file_writer(os.path.join(logdir, "test"))

In [314]:
train_features_test = pd.DataFrame(data = train_features)
train_labels_test = train_features['guten_genre']
train_features_test = train_features_test.drop('book_id', axis=1)
train_features_test = train_features_test.drop('guten_genre', axis=1)
model2.compile(loss=loss_fn, optimizer=opt, metrics=['accuracy'])
print(train_features_test.to_numpy())
print(train_labels_test.to_numpy())
model2.fit(train_features_test.to_numpy(), train_labels_test.to_numpy(), epochs=1, batch_size=batch_size, verbose=1, class_weight=w_range)

[[ 3.3884675   0.41742078  0.63066057 ...  0.10820871 -0.15805182
   0.10212437]
 [-0.3806077   0.39351069 -1.22525583 ...  0.07667653 -0.86914994
   0.5636526 ]
 [-0.67053657  0.79998222 -0.17642264 ... -0.71162807 -0.31042999
  -0.16368444]
 ...
 [-0.67053657 -0.55492288  0.26156251 ... -2.19364072  3.19426787
  -1.20376893]
 [ 0.77910774 -0.72428601 -0.13502246 ... -0.14404876  0.24828996
   0.01204322]
 [-0.09067884 -0.98849251 -0.82364995 ...  1.1172386  -0.25963727
  -0.37036627]]
[2 4 3 ... 7 2 3]
Train on 4774 samples
4774/4774 [==============================] - 3s 536us/sample - loss: 2.0946 - accuracy: 0.2468


In [323]:
#input_ in sampled_features_and_labels[0].iterrows(): 
#input_ in enumerate(sampled_features_and_labels[0]):
input_length = len(train_features)
train_acc_metric = tf.keras.metrics.SparseCategoricalAccuracy()

for epoch in range(epochs):
    for step, input_ in train_features.groupby(np.arange(input_length) // batch_size):
        #if step > train_steps:
        #    break
        dataFrame = pd.DataFrame(data = input_)
        labels_ = dataFrame.guten_genre
        labels_ = labels_.to_numpy()

        features_ = input_.drop('book_id', axis=1)
        features_ = features_.drop('guten_genre', axis=1)
        features_ = np.asarray(features_).astype(np.float32)
            
        with tf.GradientTape() as tape:
            logits = model(features_)
            xent = loss_fn(labels_, logits)

        varis = model.trainable_variables
        grads = tape.gradient(xent, varis)
      
        opt.apply_gradients(zip(grads, varis))

        train_acc_metric(labels_, logits)
        
        with train_writer.as_default():
            tf.summary.scalar("loss", xent, step=step)
            #tf.summary.histogram(("weights"), varis, step=step)
            tf.summary.histogram(("logits"), logits, step=step)
            tf.summary.histogram("output", np.argmax(logits, axis=-1), step=step)

    
        if not step % 100:
            acc = train_acc_metric.result()
            print("Epoch: {} Loss: {} Accuracy: {} OutExample: {} LabelExample: {}".format(
                epoch, xent, acc, np.argmax(logits, axis=-1), str(labels_)))
            train_acc_metric.reset_states()
            varstep = 0
            with train_writer.as_default():
                for vars in varis:                    
                    tf.summary.histogram(("weights"+str(varstep)), vars, step=step)
                    varstep = varstep + 1
                    tf.summary.scalar("accuracy", acc, step=step)

Epoch: 0 Loss: 2.1856489181518555 Accuracy: 0.125 OutExample: [3 3 4 5 1 6 2 2] LabelExample: [2 4 3 0 7 6 6 8]
Epoch: 0 Loss: 2.153493642807007 Accuracy: 0.20499999821186066 OutExample: [3 3 5 7 7 3 0 2] LabelExample: [3 6 2 0 7 5 7 4]
Epoch: 0 Loss: 2.1980180740356445 Accuracy: 0.11749999970197678 OutExample: [7 7 7 7 7 7 7 7] LabelExample: [5 3 0 3 3 5 3 4]
Epoch: 0 Loss: 2.202533483505249 Accuracy: 0.10875000059604645 OutExample: [7 7 7 7 7 7 7 7] LabelExample: [1 5 6 3 5 1 1 1]
Epoch: 0 Loss: 2.2008156776428223 Accuracy: 0.0949999988079071 OutExample: [1 1 1 1 1 1 1 1] LabelExample: [8 4 1 4 4 8 5 3]
Epoch: 0 Loss: 2.19093656539917 Accuracy: 0.11500000208616257 OutExample: [7 7 7 7 7 7 7 7] LabelExample: [7 7 1 1 5 0 2 6]


In [ ]:
%load_ext tensorboard

In [326]:
#%tensorboard --logdir logs

In [324]:
test_acc_metric = tf.keras.metrics.SparseCategoricalAccuracy()
input_length = len(test_features)
for step, input_ in test_features.groupby(np.arange(input_length) // batch_size):
    dataFrame = pd.DataFrame(data = input_)
    labels_ = dataFrame.guten_genre
    features_ = dataFrame.drop('book_id', axis=1)
    features_ = features_.drop('guten_genre', axis=1)
    features_ = np.asarray(features_).astype(np.float32)
    test_acc_metric(labels_, model(features_))
    if not step % 10:
        print(np.argmax(model(features_), axis=-1))
    if not step % 100:
        print(model(features_))
        print(features_)
print("Test acc: {}".format(test_acc_metric.result()))

[2 2 2 2 2 2 2 2]
tf.Tensor(
[[ 0.00227066 -0.00149452  0.01363323 -0.01107438 -0.01190203 -0.00367624
   0.00198645  0.00481698  0.0008062 ]
 [ 0.00227066 -0.00149452  0.01363323 -0.01107438 -0.01190203 -0.00367624
   0.00198645  0.00481698  0.0008062 ]
 [ 0.00227066 -0.00149452  0.01363323 -0.01107438 -0.01190203 -0.00367624
   0.00198645  0.00481698  0.0008062 ]
 [ 0.00227066 -0.00149452  0.01363323 -0.01107438 -0.01190203 -0.00367624
   0.00198645  0.00481698  0.0008062 ]
 [ 0.00227066 -0.00149452  0.01363323 -0.01107438 -0.01190203 -0.00367624
   0.00198645  0.00481698  0.0008062 ]
 [ 0.00227066 -0.00149452  0.01363323 -0.01107438 -0.01190203 -0.00367624
   0.00198645  0.00481698  0.0008062 ]
 [ 0.00227066 -0.00149452  0.01363323 -0.01107438 -0.01190203 -0.00367624
   0.00198645  0.00481698  0.0008062 ]
 [ 0.00227066 -0.00149452  0.01363323 -0.01107438 -0.01190203 -0.00367624
   0.00198645  0.00481698  0.0008062 ]], shape=(8, 9), dtype=float32)
[[-0.96046543  2.0193968   1.2940385

In [315]:
test_acc_metric = tf.keras.metrics.SparseCategoricalAccuracy()
input_length = len(test_features)
for step, input_ in test_features.groupby(np.arange(input_length) // batch_size):
    dataFrame = pd.DataFrame(data = input_)
    labels_ = dataFrame.guten_genre
    features_ = dataFrame.drop('book_id', axis=1)
    features_ = features_.drop('guten_genre', axis=1)
    features_ = np.asarray(features_).astype(np.float32)
    test_acc_metric(labels_, model2(features_))
    if not step % 10:
        print(np.argmax(model2(features_), axis=-1))
    if not step % 100:
        print(model2(features_))
        print(features_)
print("Test acc: {}".format(test_acc_metric.result()))

[0 0 0 0 0 0 0 0]
tf.Tensor(
[[ 0.04992972  0.00315021  0.03887487 -0.07362494 -0.0023321  -0.03541558
  -0.01961228 -0.03818445 -0.05046205]
 [ 0.04992972  0.00315021  0.03887487 -0.07362494 -0.0023321  -0.03541558
  -0.01961228 -0.03818445 -0.05046205]
 [ 0.04992972  0.00315021  0.03887487 -0.07362494 -0.0023321  -0.03541558
  -0.01961228 -0.03818445 -0.05046205]
 [ 0.04992972  0.00315021  0.03887487 -0.07362494 -0.0023321  -0.03541558
  -0.01961228 -0.03818445 -0.05046205]
 [ 0.04992972  0.00315021  0.03887487 -0.07362494 -0.0023321  -0.03541558
  -0.01961228 -0.03818445 -0.05046205]
 [ 0.04992972  0.00315021  0.03887487 -0.07362494 -0.0023321  -0.03541558
  -0.01961228 -0.03818445 -0.05046205]
 [ 0.04992972  0.00315021  0.03887487 -0.07362494 -0.0023321  -0.03541558
  -0.01961228 -0.03818445 -0.05046205]
 [ 0.04992972  0.00315021  0.03887487 -0.07362494 -0.0023321  -0.03541558
  -0.01961228 -0.03818445 -0.05046205]], shape=(8, 9), dtype=float32)
[[-0.96046543  2.0193968   1.2940385